### ISSUE TITLE
Basic Synthesizers

### ISSUE THREAD

**Issue by jsmith** [vuesic/vuesic#19]
Initially, we need basic synthesizers to be able to test our system. This should take advantage of [Tone.js](https://tonejs.github.io/docs/r12/Synth) for actually producing the sound.

They should look something very similar to this: https://codepen.io/gridsound/pen/opEMyj

For now, we probably don't have to show the waveform and could just display text.

**Comment by alexodonn** [comment]
Was this fully taken care of with PR #28?
